<form action="index.php" method="POST">
    <fieldset>
        <label>Prenom</label>
        <input type="text" name="first_name">
    </fieldset>
    <fieldset>
        <label>Nom</label>
        <input type="text" name="last_name">
    </fieldset>
    <fieldset>
        <label>Email</label>
        <input type="email" name="emailRegister">
    </fieldset>
    <fieldset>
        <label>Password</label>
        <input type="password" name="passwordRegister">
    </fieldset>
    <fieldset>
        <label>Confirmer Password</label>
        <input type="password" name="confirm-password">
    </fieldset>
        <input type="hidden" name="registerForm">
    <input type="submit" name="registerSubmit" value="S'inscrire">
</form>