<form action="index.php" method="POST">
    
    <fieldset>
        <label>Login</label>
        <input type="email" name="emailLog">
    </fieldset>
    
    <fieldset>
        <label>Password</label>
        <input type="password" name="passwordLog">
    </fieldset>
    
    <fieldset>
        <input type="hidden" name="loginForm">
    </fieldset>
    
        <input type="submit" name="connect" value="Se connecter">
        
</form>