<form action="" method="POST">
    <fieldset>
        <label>Titre</label>
        <input type="text" name="postTitle">
    </fieldset>
    <fieldset>
        <label>Contenu</label>
        <input type="text" name="content">
    </fieldset>
    <fieldset>
        <label>Auteur</label>
        <input type="text" name="author">
    </fieldset>
    <fieldset>
        <label>Categorie</label>
        <select>
            <option>-Selectionner une catégorie-</option>
            <option>Cat1</option>
            <option>Cat2</option>
            <option>Cat3</option>
        </select>
    </fieldset>
</form>