<?php 
require '_post-create.phtml';
require '_post-edit.phtml';
?>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Content</th>
            <th>Author</th>
            <th>Category</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Post1</td>
            <td>Content</td>
            <td>Author</td>
            <td>Category</td>
        </tr>
        <tr>
            <td>Post2</td>
            <td>Content</td>
            <td>Author</td>
            <td>Category</td>
        </tr>
    </tbody>
</table>